version: "3.3"

services:
  bss_db:
    image: mysql:8
    cap_add:
      - SYS_NICE
    volumes:
      - ./data/:/docker-entrypoint-initdb.d/
      - /etc/localtime:/etc/localtime:ro
      - type: bind
        source: ./cnf/my.cnf
        target: /etc/mysql/conf.d/my.cnf
    restart: always
    container_name: chatting-mysql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: chatting
      MYSQL_USER: chat-user
      MYSQL_PASSWORD: my-secret-pw
    command: --default-time-zone=Asia/Seoul
    ports:
      - "17777:3306"
    expose:
      - "17777"

